
spring:
    view:
        prefix: /WEB-INF/views/
        suffix: .jsp
# MONGODB (MongoProperties)
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: manasobi
        
server.port: 80

spring.dao.exceptiontranslation.enabled: false


logging.level: 
    io.recruit: INFO
    org.springframework: INFO
    org.apache.tomcat.util.net.NioSelectorPool: INFO

logging.config: classpath:config/logback.xml
    
